server:
  port: 8080
spring:
  application:
    name: microservice-gateway-springcloud-gateway2
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
dynamic:
  route:
    server-addr: localhost:8848   # nacos config
    namespace: public
    group: DEFAULT_GROUP
    data-id: microservice-gateway-springcloud-gateway2-dynamic-route
logging:
  level:
    org.springframework.cloud.gateway: debug
management:
  endpoints:
    web:
      exposure:
        exclude: "*"