server:
  port: 8082
spring:
  application:
    name: microservice-gateway-payment-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848    # standalone
#        server-addr: localhost:8848,localhost:8849,localhost:8850    # cluster